const s = (v: unknown): string => (typeof v === "string" ? v : String(v ?? ""));
const n = (v: unknown): number => (typeof v === "number" ? v : Number(v));

export const transformToBusinessRequest = (data: Record<string, unknown>): BusinessRequest => {
  return {
    LEAD_PRODUCT_EN: s(data.LEAD_PRODUCT_EN),
    LEAD_PRODUCT_FR: s(data.LEAD_PRODUCT_FR),
    PRODUCTS_EN: s(data.PRODUCTS_EN),
    PRODUCTS_FR: s(data.PRODUCTS_FR),
    BR_NMBR: n(data.BR_NMBR),
    BR_SHORT_TITLE: s(data.BR_SHORT_TITLE),
    RPT_GC_ORG_NAME_EN: s(data.RPT_GC_ORG_NAME_EN),
    RPT_GC_ORG_NAME_FR: s(data.RPT_GC_ORG_NAME_FR),
    ORG_TYPE_EN: s(data.ORG_TYPE_EN),
    ORG_TYPE_FR: s(data.ORG_TYPE_FR),
    REQST_IMPL_DATE: s(data.REQST_IMPL_DATE),
    BR_TYPE_EN: s(data.BR_TYPE_EN),
    BR_TYPE_FR: s(data.BR_TYPE_FR),
    PRIORITY_EN: s(data.PRIORITY_EN),
    PRIORITY_FR: s(data.PRIORITY_FR),
    SUBMIT_DATE: s(data.SUBMIT_DATE),
    RVSD_TARGET_IMPL_DATE: s(data.RVSD_TARGET_IMPL_DATE),
    CPLX_EN: s(data.CPLX_EN),
    CPLX_FR: s(data.CPLX_FR),
    ACTUAL_IMPL_DATE: s(data.ACTUAL_IMPL_DATE),
    AGRMT_END_DATE: s(data.AGRMT_END_DATE),
    SCOPE_EN: s(data.SCOPE_EN),
    SCOPE_FR: s(data.SCOPE_FR),
    CLIENT_SUBGRP_EN: s(data.CLIENT_SUBGRP_EN),
    CLIENT_SUBGRP_FR: s(data.CLIENT_SUBGRP_FR),
    GROUP_EN: s(data.GROUP_EN),
    GROUP_FR: s(data.GROUP_FR),
    BR_ACTIVE_EN: s(data.BR_ACTIVE_EN),
    BR_ACTIVE_FR: s(data.BR_ACTIVE_FR),
    BITS_STATUS_EN: s(data.BITS_STATUS_EN),
    BITS_STATUS_FR: s(data.BITS_STATUS_FR),
    ASSOC_BRS: s(data.ASSOC_BRS),
    ACC_MANAGER_OPI: s(data.ACC_MANAGER_OPI),
    AGR_OPI: s(data.AGR_OPI),
    BA_OPI: s(data.BA_OPI),
    BA_PRICING_OPI: s(data.BA_PRICING_OPI),
    BA_PRICING_TL: s(data.BA_PRICING_TL),
    BA_TL: s(data.BA_TL),
    CSM_DIRECTOR: s(data.CSM_DIRECTOR),
    EAOPI: s(data.EAOPI),
    PM_OPI: s(data.PM_OPI),
    QA_OPI: s(data.QA_OPI),
    SDM_TL_OPI: s(data.SDM_TL_OPI),
    BR_OWNER: s(data.BR_OWNER),
    TEAMLEADER: s(data.TEAMLEADER),
    WIO_OPI: s(data.WIO_OPI),
    GCIT_CAT_EN: s(data.GCIT_CAT_EN),
    GCIT_CAT_FR: s(data.GCIT_CAT_FR),
    GCIT_PRIORITY_EN: s(data.GCIT_PRIORITY_EN),
    GCIT_PRIORITY_FR: s(data.GCIT_PRIORITY_FR),
    TARGET_IMPL_DATE: s(data.TARGET_IMPL_DATE),
    IO_ID: s(data.IO_ID),
    EPS_NMBR: s(data.EPS_NMBR),
    ECD_NMBR: s(data.ECD_NMBR),
    PROD_OPI: s(data.PROD_OPI),
    PHASE_EN: s(data.PHASE_EN),
    PHASE_FR: s(data.PHASE_FR),
    SOLN_OPI: s(data.SOLN_OPI),
  };
};
